### ISSUE TITLE
[Docs] Exclude containers for rabbit / async / events / notifications

### ISSUE THREAD

**Issue by lonix1** [taigaio/taiga-docker#36]
Thank you for this nice docker image. Dockerising taiga4 was not easy, so I'm glad it's been done officially now! :+1:

However I don't need the realtime stuff - notifications, async, events, rabbitmq, etc. When working alone, that stuff isn't necessary (and consumes huge amounts of memory and cpu) - so in my taiga4 docker files, I excluded them.

Please provide alternate examples which show how to exclude that stuff? It's seems more complicated in taiga5, so I'm not sure which containers I can exclude.

Thank you for this great app!

**Comment by yamila-moreno** [comment]
Hi @lonix1 thanks for your kind words.

Currently we offer and support these official images, which provide the features as their best, to enjoy all the options of Taiga and the best experiencie.

In the future, we may provide simpler images for demo purposes, but meanwhile, you can:
- create a custom configuration and map config files instead of using the environment variables
-  edit docker-compose and comment the services you think you won't need

Good Luck!

**Comment by lonix1** [comment]
I don't think you should support alternate docker files, as it's complicated enough already! :smile: I just need to know the basics and I'll do it myself.

In taiga4 to support event notification, you had rabbitmq and "events". Now there are others too.

If I don't need notifications, can I remove:
- taiga-async
- taiga-async-rabbitmq
- taiga-events
- taiga-events-rabbitmq
- taiga-gateway
