### ISSUE TITLE
[BUG] Instructions for docker-compose are complete and utter bogus

### ISSUE THREAD

**Issue by robinduckett** [taigaio/taiga-docker#66]
When attempting to follow the instructions on the repo for installation I encountered the following issues:

1. The system failed to start and complained that a large number of migrations were required, which is not mentioned at all in the instructions given
2. The instructions given to resolve the migration issue in the CLI were incorrect, referencing a manage.py when the README only references the `taiga-manage.sh` file
3. Upon completion of the migration, the system is left in a state where the nginx instance is not running
4. After re-running `launch-all.sh` the system boots although not in a way that worked for me (my docker host is running on another machine, so I had to update docker-compose.yml to change instances of localhost to my docker hosts' IP Address)
5. Upon running the given `createsuperuser` command, which appeared to run successfully, the user was created in the database, but the login with that user fails, and thus the system is entirely unusable

The whole experience has turned me off from running Taiga and I will now find another solution. Please take this constructively. I have been a software engineer for over a decade, and have plenty of experience with most of this stack (docker, nginx, rabbitmq etc) so I know it can be difficult to get it working, but it should be fairly realistic to expect that documentation is kept up to date. This is not to mention the effective labyrinth of archived and dead projects I had to traverse in order to submit this issue to the right project.

**Comment by daniel-herrero** [comment]
Hi @robinduckett,

Which installation document are you following? It seems you're referring to the [source code installation](https://docs.taiga.io/setup-production.html#taiga-back) and that you're facing problem when running the 2.7 backend setup, but you indeed metion you're running it from docker.
![image](https://user-images.githubusercontent.com/4539017/165247060-aadbd535-9eaf-45e1-aec9-4e08453be2a1.png)

The correct document to follow the instructions from is [this one](https://docs.taiga.io/setup-production.html#setup-prod-with-docker), and as far as we know it's updated and working properly. The REDME.md from taiga-docker repository is just a simplified version of the complete installation guide.

We'd suggest you to repeat a clean installation following that guide as it'll probably solve your issues. If you still find a problem please report back in order to solve any potential bug that may exist.

**Comment by robinduckett** [comment]
Okay I'll try it but to be fair I switched to something else months ago.
