### ISSUE TITLE
Taiga Something happened and the Taiga has captured the error to be able to work on it

### ISSUE THREAD

**Issue by vishnukv64** [taigaio/taiga-docker#69]
A Clean install on ubuntu 18.04 using docker

Start the application
$ ./launch-all.sh

After some instants, when the application is started you can proceed to create the superuser with the following script:
$ ./taiga-manage.sh createsuperuser

Was using a cloud ubuntu server ( 18.04 )
I installed everything according to the instructions. I got to launch. Everything started successfully. I open the page (http://cloudserverip:9000 ) and it says:
[Taiga.] Something happened and the Taiga has captured the error to be able to work on it.

I saw a lot of people rainsing this issue, but i still cant understand the bug? 
there no errors raised during installation - followed the instructions.

Adding a screenshot below
![Screenshot from 2021-03-29 01-17-00](https://user-images.githubusercontent.com/33051467/112765838-b421b200-902c-11eb-8880-d93978690a08.png)

**Comment by yamila-moreno** [comment]
Hi @vishnukv64 as it's explained in the bug template, we need more information to help you, before we can tell it's a bug:

- do you see something in the dev-tools? (press F12 and go to "console")
- do you see something in the docker-compose logs?
- share your `docker-compose.yml` (**with all the credentials redacted**)

**Comment by vishnukv64** [comment]
Hi, @yamila-moreno, 
I haven't customized/edited anything on the docker-compose file.
Yes, in the dev tools, i am getting errors, attaching the screenshot below.

![Screenshot from 2021-03-29 18-33-45](https://user-images.githubusercontent.com/33051467/112841624-563daa80-90be-11eb-8fe7-7deb40e33e7f.png)

note: There were no errors while buidling the docker compose !!

**Comment by yamila-moreno** [comment]
Hi @vishnukv64 `docker-compose.yml` is configured with default values, as `http://localhost:9000`.

You should go through the file and change, at least:
- credentials
- TAIGA_SECRET_KEY
- TAIGA_SITES_DOMAIN
- TAIGA_URL
- TAIGA_WEBSOCKETS_URL

Let me know if this helps; good luck!

**Comment by vishnukv64** [comment]
Yes, it worked . thank you for the help!!!

**Comment by Cyber1000** [comment]
Sorry to write in an old thread, but I ran into the same issue:
- Just wanted to start this docker-container to test taiga a little bit
-  Readme here just says: "The docker-compose.yml has some environment variables of configuration with default values that we strongly recommend to change. "
- I understand that I should change the values in a production environment, but I wouldn't expect it just while tinkering around. If you don't change TAIGA_SITES_DOMAIN, TAIGA_URL and TAIGA_WEBSOCKETS_URL away from localhost it will definitely crash as said in this issue with no further explaination that the frontend wants to connect to localhost:9000.

I think this would be worth to mention in "Getting Started" of this repo

**Comment by daniel-herrero** [comment]
Hi @Cyber1000,

We have perform a fresh installation without changing anything in the configuration, in order to reproduce your issue, but everything starts as it should. We suggest you to revert any local change you may have, and re-start again using `$ ./launch-taiga.sh`.

If the same occurs, please, give us further details, like dev-tools (press F12 and go to "console"), docker-compose logs, and your docker-compose.yml configuration.

Greetings

**Comment by Cyber1000** [comment]
Well I've to say that my docker-server and the computer I'm testing on are not the same. Could this explain the differences? At least I'm getting exactly the same in dev-tools like the screenshot in https://github.com/taigaio/taiga-docker/issues/69#issuecomment-809365622?

Maybe it was to late when testing this :-) But maybe it should find its way in the getting started, it says "Default access for the application is http://localhost:9000", but it doesn't say, that I can't access the site from another computer (without changing all localhosts in docker-compose.yml)

It seems that @vishnukv64 also didn't use localhost, but "http://cloudserverip:9000", so I'm not the only one, who made this mistake.

Sorry if I didn't clearly express this in my first comment.

**Comment by daniel-herrero** [comment]
Ok, @Cyber1000 I think I now understand your problem.
I have added an issue in taiga to fix the documentation in order to avoid any potential future mistakes.
https://tree.taiga.io/project/taiga/issue/4445

I hope this solution suits you.

**Comment by rodrigobrochado** [comment]
Hi @daniel-herrero, allow me to bring this back again with a feedback. I was still "defeated" by the domain name configuration. Even with this issue and the corrections made on the docs, I take some hours figuring it out haha. It seems that [others](https://groups.google.com/g/taigaio/c/f7CvT4jRAx4/m/51ngQTjwBAAJ) also are having issues with that.

In my case, I was using `wss://my.domain.com:9000` for `TAIGA_WEBSOCKETS_URL`, instead of `wss://my.domain.com`. I think that this [doc](https://docs.taiga.io/setup-production.html#setup-prod-with-docker) line is specially confusing for non-specialists on server hosting:  
`"This should have the same value as TAIGA_SITES_DOMAIN, ie: ws://taiga.mycompany.com."`

where `TAIGA_SITES_DOMAIN` was declared above as `"localhost:9000"`. We can see that it's not the **same** value, of course, so I thought there was some flexibility there and let the port on the URL env var.

Besides, the schemes should be changed to https and wss when using secure connections (that is the most cases when using taiga with a domain name in a server), although the nginx redirects the calls to http, even when secured. I could only find that info on other issues on github. 

It would be nice if the port suppression on TAIGA*URL's env var and scheme modification would be added next to the proxy example at the bottom of the docker-related documentation.
Thanks a lot!
